import { Link } from "@tanstack/react-router"
import { useEffect, useState } from "react"
import { EventCard, ErrorState, LoadingState, PageTitle, PortCard, Severity, ShippingShell, StatCard, StatusBadge, VesselCard, VoyageCard, formatDate, formatStatus, useShipping } from "./app"
import { myFetch } from "~/utils"

export function HotPage() {
  const { data, isLoading, isError } = useShipping()
  return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="运营态势" title="Shipping HOT" description="面向关注船舶、港口、航次和航运信号的本地指挥台。" /><div className="grid gap-4 md:grid-cols-4"><StatCard label="活跃 HOT" value={data.hot.length} tone="critical" /><StatCard label="关注船舶" value={data.vessels.filter(v => v.isWatched).length} /><StatCard label="关注港口" value={data.ports.filter(p => p.isWatched).length} tone="warning" /><StatCard label="数据源" value={`${data.provider.vessel} / ${data.provider.weather}`} /></div><section className="mt-8"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs uppercase tracking-wider text-primary">优先信号</p><h2 className="text-2xl font-bold">需要关注的事项</h2></div><span className="text-sm op-60">V1 Provider：AISStream / Open-Meteo Marine</span></div><div className="grid gap-4 lg:grid-cols-2">{data.hot.map(item => <article key={item.id} className="hot-card"><div className="flex items-center justify-between"><Severity value={item.severity} /><StatusBadge stale={item.freshness === "stale"} sourceStatus={item.sourceStatus} /></div><h3 className="mt-3 text-xl font-bold">{item.title}</h3><p className="mt-1 op-70">{item.summary}</p><p className="mt-4 text-sm op-60">{item.relatedLabel ?? "航运信号"} · {formatDate(item.occurredAt)}</p></article>)}</div></section><section className="mt-8 grid gap-4 lg:grid-cols-2"><div className="section-panel"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold">关注的船舶</h2><Link to="/vessels" className="text-sm text-primary">查看全部 →</Link></div>{data.vessels.filter(v => v.isWatched).map(v => <Link key={v.id} to="/vessels/$id" params={{ id: v.id }} className="list-row"><span className="font-semibold">{v.name}</span><span className="op-60">{formatStatus(v.navigationStatus)}</span></Link>)}</div><div className="section-panel"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold">关注的港口</h2><Link to="/ports" className="text-sm text-primary">查看全部 →</Link></div>{data.ports.filter(p => p.isWatched).map(p => <Link key={p.id} to="/ports/$id" params={{ id: p.id }} className="list-row"><span className="font-semibold">{p.name}</span><span className="op-60">拥堵等级：{formatStatus(p.congestionLevel)}</span></Link>)}</div></section></>}</ShippingShell>
}

export function VesselsPage() { const { data, isLoading, isError, refetch } = useShipping(); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="运营数据" title="我的船舶" description="查看关注船队的航行状态、位置、目的地和数据新鲜度。" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{data.vessels.map(v => <div key={v.id} className="relative"><Link to="/vessels/$id" params={{ id: v.id }}><VesselCard vessel={v} /></Link><WatchButton kind="vessel" id={v.id} watched={v.isWatched} onSaved={() => refetch()} /></div>)}</div></>}</ShippingShell> }
export function VesselDetailPage({ id }: { id: string }) { const { data, isLoading, isError } = useShipping(); const vessel = data?.vessels.find(v => v.id === id); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data || !vessel ? <ErrorState /> : <><PageTitle eyebrow="船舶详情" title={vessel.name} description={`${vessel.carrier ?? "未知船公司"} · ${vessel.shipType ?? "船舶"}`} /><div className="grid gap-4 md:grid-cols-4"><StatCard label="航行状态" value={formatStatus(vessel.navigationStatus)} /><StatCard label="航速" value={`${vessel.speed ?? "—"} 节`} /><StatCard label="目的地" value={vessel.destination ?? "—"} /><StatCard label="更新时间" value={formatDate(vessel.updatedAt)} /></div><div className="mt-6 section-panel"><h2 className="text-xl font-bold">当前状态</h2><dl className="detail-grid mt-4"><dt>IMO</dt><dd>{vessel.imo ?? "—"}</dd><dt>MMSI</dt><dd>{vessel.mmsi ?? "—"}</dd><dt>位置</dt><dd>{vessel.latitude}, {vessel.longitude}</dd><dt>状态开始于</dt><dd>{formatDate(vessel.statusChangedAt)}</dd><dt>数据源</dt><dd><StatusBadge stale={vessel.stale} sourceStatus={vessel.sourceStatus} /></dd></dl></div></>}</ShippingShell> }

export function PortsPage() { const { data, isLoading, isError, refetch } = useShipping(); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="运营数据" title="我的港口" description="查看重点港口的拥堵、等待船舶和运营状态。" /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{data.ports.map(p => <div key={p.id} className="relative"><Link to="/ports/$id" params={{ id: p.id }}><PortCard port={p} /></Link><WatchButton kind="port" id={p.id} watched={p.isWatched} onSaved={() => refetch()} /></div>)}</div></>}</ShippingShell> }
export function PortDetailPage({ id }: { id: string }) { const { data, isLoading, isError } = useShipping(); const port = data?.ports.find(p => p.id === id); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data || !port ? <ErrorState /> : <><PageTitle eyebrow="港口详情" title={port.name} description={`${port.nameEn} · ${port.country} · ${port.unlocode}`} /><div className="grid gap-4 md:grid-cols-4"><StatCard label="拥堵等级" value={formatStatus(port.congestionLevel)} tone={port.congestionLevel === "critical" ? "critical" : "warning"} /><StatCard label="等待船舶" value={port.waitingVessels} /><StatCard label="其中集装箱船" value={port.containerWaitingVessels} /><StatCard label="等待时长" value={`${port.waitingHours} 小时`} /></div><div className="mt-6 section-panel"><h2 className="text-xl font-bold">运营状态</h2><dl className="detail-grid mt-4"><dt>状态</dt><dd>{formatStatus(port.operationalStatus)}</dd><dt>最后更新</dt><dd>{formatDate(port.updatedAt)}</dd><dt>数据源</dt><dd><StatusBadge stale={port.stale} sourceStatus={port.sourceStatus} /></dd></dl></div></>}</ShippingShell> }

export function VoyagesPage() { const { data, isLoading, isError } = useShipping(); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="航次计划" title="航次" description="对比跟踪基线与本地可用的最新计划时间。" /><div className="grid gap-4 md:grid-cols-2">{data.voyages.map(v => <Link key={v.id} to="/voyages/$id" params={{ id: v.id }}><VoyageCard voyage={v} vessels={data.vessels} ports={data.ports} /></Link>)}</div></>}</ShippingShell> }
export function VoyageDetailPage({ id }: { id: string }) { const { data, isLoading, isError } = useShipping(); const voyage = data?.voyages.find(v => v.id === id); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data || !voyage ? <ErrorState /> : <><PageTitle eyebrow="航次详情" title={voyage.voyageNumber} description={`${data.vessels.find(v => v.id === voyage.vesselId)?.name ?? "船舶"} · 计划对比`} /><VoyageCard voyage={voyage} vessels={data.vessels} ports={data.ports} /><div className="mt-6 section-panel"><h2 className="text-xl font-bold">计划时间证据</h2><dl className="detail-grid mt-4"><dt>基准 ETA</dt><dd>{formatDate(voyage.baselineEta)} · {voyage.baselineEtaSource}</dd><dt>最新 ETA</dt><dd>{formatDate(voyage.latestEta)} · {voyage.latestEtaSource}</dd><dt>延误</dt><dd>{voyage.delayMinutes === undefined ? "未知" : `${voyage.delayMinutes} 分钟`}</dd><dt>观测时间</dt><dd>{formatDate(voyage.latestEtaObservedAt)}</dd></dl></div></>}</ShippingShell> }

export function EventsPage() { const [showResolved, setShowResolved] = useState(false); const { data, isLoading, isError } = useShipping(); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="事件生命周期" title="事件" description="包含证据、去重、严重程度变化和明确解决状态的运营异常。" /><div className="mb-5 flex gap-2"><button className={`filter-button ${!showResolved ? "selected" : ""}`} onClick={() => setShowResolved(false)}>进行中</button><button className={`filter-button ${showResolved ? "selected" : ""}`} onClick={() => setShowResolved(true)}>已解决</button></div><div className="grid gap-4 lg:grid-cols-2">{data.events.filter(e => showResolved ? e.status === "resolved" : e.status === "active").map(e => <EventCard key={e.id} event={e} label={e.vesselId ? data.vessels.find(v => v.id === e.vesselId)?.name : e.portId ? data.ports.find(p => p.id === e.portId)?.nameEn : e.voyageId ? data.voyages.find(v => v.id === e.voyageId)?.voyageNumber : undefined} />)}</div></>}</ShippingShell> }

export function FeedPage() { const { data, isLoading, isError } = useShipping(); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="信息资讯" title="航运资讯" description="结构化展示港口通知、天气信号和船公司信息。" /><div className="grid gap-4 lg:grid-cols-2">{data.feedItems.map(item => <article key={item.id} className="data-card"><div className="flex items-center justify-between"><Severity value={item.severity} /><StatusBadge stale={item.stale} sourceStatus={item.sourceStatus} /></div><h2 className="mt-3 text-xl font-bold">{item.title}</h2><p className="mt-2 op-70">{item.summary}</p><div className="mt-4 flex flex-wrap gap-3 text-xs op-60"><span>{formatStatus(item.category)}</span><span>{formatDate(item.publishedAt)}</span><span>数据源：{item.sourceId}</span></div><a className="mt-4 inline-block text-sm text-primary" href={item.sourceUrl} target="_blank" rel="noreferrer">打开来源 →</a></article>)}</div></>}</ShippingShell> }

export function SettingsPage() { const { data, isLoading, isError, refetch } = useShipping(); const [saved, setSaved] = useState(false); const [refreshInterval, setRefreshInterval] = useState(15); const [anchoredHours, setAnchoredHours] = useState(2); const [delayMinutes, setDelayMinutes] = useState(60); const [retentionDays, setRetentionDays] = useState(30); const [congestionLevel, setCongestionLevel] = useState("high"); useEffect(() => { if (data) { setRefreshInterval(data.settings.refreshInterval); setAnchoredHours(data.settings.eventThresholds.anchoredHours); setDelayMinutes(data.settings.eventThresholds.delayMinutes); setRetentionDays(data.settings.retentionDays); setCongestionLevel(data.settings.eventThresholds.congestionLevel) } }, [data]); if (isLoading) return <ShippingShell><LoadingState /></ShippingShell>; if (isError || !data) return <ShippingShell><ErrorState /></ShippingShell>; return <ShippingShell><PageTitle eyebrow="本地配置" title="设置" description="配置刷新间隔和确定性的事件阈值。船舶与港口的关注状态单独保存。" /><div className="section-panel max-w-2xl"><label className="setting-row"><span><strong>刷新间隔</strong><small>本地数据刷新间隔（分钟）</small></span><input value={refreshInterval} onChange={e => setRefreshInterval(Number(e.target.value))} type="number" min="1" /></label><label className="setting-row"><span><strong>锚泊告警阈值</strong><small>锚泊多少小时后生成事件</small></span><input value={anchoredHours} onChange={e => setAnchoredHours(Number(e.target.value))} type="number" min="1" /></label><label className="setting-row"><span><strong>ETA 延误阈值</strong><small>航次延误多少分钟后升级提醒</small></span><input value={delayMinutes} onChange={e => setDelayMinutes(Number(e.target.value))} type="number" min="1" /></label><label className="setting-row"><span><strong>拥堵阈值</strong><small>达到或超过此港口等级时告警</small></span><select value={congestionLevel} onChange={e => setCongestionLevel(e.target.value)}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label className="setting-row"><span><strong>数据保留</strong><small>事件和资讯的保留天数</small></span><input value={retentionDays} onChange={e => setRetentionDays(Number(e.target.value))} type="number" min="1" /></label><button className="primary-button mt-6" onClick={async () => { await myFetch("/shipping/settings", { method: "POST", body: { refreshInterval, retentionDays, eventThresholds: { anchoredHours, delayMinutes, congestionLevel } } }); await refetch(); setSaved(true) }}>{saved ? "已在本地保存" : "保存设置"}</button><p className="mt-4 text-sm op-60">V1 数据源：AISStream（船位，可选 key）/ Open-Meteo Marine（天气，无需普通使用 key）/ Mock Port 与 Schedule。</p></div></ShippingShell> }

function WatchButton({ kind, id, watched, onSaved }: { kind: "vessel" | "port", id: string, watched: boolean, onSaved: () => void }) {
  return <button className="absolute right-7 top-7 z-2 rounded-lg bg-base/80 px-3 py-2 text-sm text-primary shadow" onClick={async (event) => { event.preventDefault(); await myFetch("/shipping/watch", { method: "POST", body: { kind, id } }); onSaved() }}>{watched ? "已关注" : "关注"}</button>
}
