import { Link } from "@tanstack/react-router"
import { useEffect, useState } from "react"
import { EventCard, ErrorState, LoadingState, PageTitle, PortCard, Severity, ShippingShell, StatCard, StatusBadge, VesselCard, VoyageCard, formatDate, formatStatus, useShipping } from "./app"
import { myFetch } from "~/utils"

export function HotPage() {
  const { data, isLoading, isError } = useShipping()
  return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="Operational intelligence" title="Shipping HOT" description="A local-first command center for watched vessels, ports, voyages and shipping signals." /><div className="grid gap-4 md:grid-cols-4"><StatCard label="Active HOT" value={data.hot.length} tone="critical" /><StatCard label="Watched vessels" value={data.vessels.filter(v => v.isWatched).length} /><StatCard label="Watched ports" value={data.ports.filter(p => p.isWatched).length} tone="warning" /><StatCard label="Provider" value="Mock" /></div><section className="mt-8"><div className="mb-4 flex items-end justify-between"><div><p className="text-xs uppercase tracking-wider text-primary">Prioritized signals</p><h2 className="text-2xl font-bold">What needs attention</h2></div><span className="text-sm op-60">Real providers: deferred</span></div><div className="grid gap-4 lg:grid-cols-2">{data.hot.map(item => <article key={item.id} className="hot-card"><div className="flex items-center justify-between"><Severity value={item.severity} /><StatusBadge stale={item.freshness === "stale"} sourceStatus={item.sourceStatus} /></div><h3 className="mt-3 text-xl font-bold">{item.title}</h3><p className="mt-1 op-70">{item.summary}</p><p className="mt-4 text-sm op-60">{item.relatedLabel ?? "Shipping signal"} · {formatDate(item.occurredAt)}</p></article>)}</div></section><section className="mt-8 grid gap-4 lg:grid-cols-2"><div className="section-panel"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold">Watched vessels</h2><Link to="/vessels" className="text-sm text-primary">View all →</Link></div>{data.vessels.filter(v => v.isWatched).map(v => <Link key={v.id} to="/vessels/$id" params={{ id: v.id }} className="list-row"><span className="font-semibold">{v.name}</span><span className="op-60">{formatStatus(v.navigationStatus)}</span></Link>)}</div><div className="section-panel"><div className="mb-4 flex justify-between"><h2 className="text-xl font-bold">Watched ports</h2><Link to="/ports" className="text-sm text-primary">View all →</Link></div>{data.ports.filter(p => p.isWatched).map(p => <Link key={p.id} to="/ports/$id" params={{ id: p.id }} className="list-row"><span className="font-semibold">{p.nameEn}</span><span className="op-60 capitalize">{p.congestionLevel} congestion</span></Link>)}</div></section></>}</ShippingShell>
}

export function VesselsPage() { const { data, isLoading, isError, refetch } = useShipping(); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="Operational data" title="My Vessels" description="Watched fleet state with navigation, position, destination and freshness." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{data.vessels.map(v => <div key={v.id} className="relative"><Link to="/vessels/$id" params={{ id: v.id }}><VesselCard vessel={v} /></Link><WatchButton kind="vessel" id={v.id} watched={v.isWatched} onSaved={() => refetch()} /></div>)}</div></>}</ShippingShell> }
export function VesselDetailPage({ id }: { id: string }) { const { data, isLoading, isError } = useShipping(); const vessel = data?.vessels.find(v => v.id === id); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data || !vessel ? <ErrorState /> : <><PageTitle eyebrow="Vessel detail" title={vessel.name} description={`${vessel.carrier ?? "Unknown carrier"} · ${vessel.shipType ?? "Vessel"}`} /><div className="grid gap-4 md:grid-cols-4"><StatCard label="Navigation" value={formatStatus(vessel.navigationStatus)} /><StatCard label="Speed" value={`${vessel.speed ?? "—"} kn`} /><StatCard label="Destination" value={vessel.destination ?? "—"} /><StatCard label="Updated" value={formatDate(vessel.updatedAt)} /></div><div className="mt-6 section-panel"><h2 className="text-xl font-bold">Current state</h2><dl className="detail-grid mt-4"><dt>IMO</dt><dd>{vessel.imo ?? "—"}</dd><dt>MMSI</dt><dd>{vessel.mmsi ?? "—"}</dd><dt>Position</dt><dd>{vessel.latitude}, {vessel.longitude}</dd><dt>Status since</dt><dd>{formatDate(vessel.statusChangedAt)}</dd><dt>Source</dt><dd><StatusBadge stale={vessel.stale} sourceStatus={vessel.sourceStatus} /></dd></dl></div></>}</ShippingShell> }

export function PortsPage() { const { data, isLoading, isError, refetch } = useShipping(); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="Operational data" title="My Ports" description="Port congestion, waiting vessels and operational status for the places that matter." /><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{data.ports.map(p => <div key={p.id} className="relative"><Link to="/ports/$id" params={{ id: p.id }}><PortCard port={p} /></Link><WatchButton kind="port" id={p.id} watched={p.isWatched} onSaved={() => refetch()} /></div>)}</div></>}</ShippingShell> }
export function PortDetailPage({ id }: { id: string }) { const { data, isLoading, isError } = useShipping(); const port = data?.ports.find(p => p.id === id); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data || !port ? <ErrorState /> : <><PageTitle eyebrow="Port detail" title={port.nameEn} description={`${port.name} · ${port.country} · ${port.unlocode}`} /><div className="grid gap-4 md:grid-cols-4"><StatCard label="Congestion" value={port.congestionLevel} tone={port.congestionLevel === "critical" ? "critical" : "warning"} /><StatCard label="Waiting vessels" value={port.waitingVessels} /><StatCard label="Container vessels" value={port.containerWaitingVessels} /><StatCard label="Waiting hours" value={port.waitingHours} /></div><div className="mt-6 section-panel"><h2 className="text-xl font-bold">Operational state</h2><dl className="detail-grid mt-4"><dt>Status</dt><dd>{port.operationalStatus}</dd><dt>Last update</dt><dd>{formatDate(port.updatedAt)}</dd><dt>Source</dt><dd><StatusBadge stale={port.stale} sourceStatus={port.sourceStatus} /></dd></dl></div></>}</ShippingShell> }

export function VoyagesPage() { const { data, isLoading, isError } = useShipping(); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="Schedules" title="Voyages" description="Compare tracking baselines with the latest locally available schedule observations." /><div className="grid gap-4 md:grid-cols-2">{data.voyages.map(v => <Link key={v.id} to="/voyages/$id" params={{ id: v.id }}><VoyageCard voyage={v} vessels={data.vessels} ports={data.ports} /></Link>)}</div></>}</ShippingShell> }
export function VoyageDetailPage({ id }: { id: string }) { const { data, isLoading, isError } = useShipping(); const voyage = data?.voyages.find(v => v.id === id); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data || !voyage ? <ErrorState /> : <><PageTitle eyebrow="Voyage detail" title={voyage.voyageNumber} description={`${data.vessels.find(v => v.id === voyage.vesselId)?.name ?? "Vessel"} · schedule comparison`} /><VoyageCard voyage={voyage} vessels={data.vessels} ports={data.ports} /><div className="mt-6 section-panel"><h2 className="text-xl font-bold">Schedule evidence</h2><dl className="detail-grid mt-4"><dt>Baseline ETA</dt><dd>{formatDate(voyage.baselineEta)} · {voyage.baselineEtaSource}</dd><dt>Latest ETA</dt><dd>{formatDate(voyage.latestEta)} · {voyage.latestEtaSource}</dd><dt>Delay</dt><dd>{voyage.delayMinutes === undefined ? "Unknown" : `${voyage.delayMinutes} minutes`}</dd><dt>Observed</dt><dd>{formatDate(voyage.latestEtaObservedAt)}</dd></dl></div></>}</ShippingShell> }

export function EventsPage() { const [showResolved, setShowResolved] = useState(false); const { data, isLoading, isError } = useShipping(); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="Event lifecycle" title="Events" description="Evidence-bearing anomalies with deduplication, severity changes and explicit resolution." /><div className="mb-5 flex gap-2"><button className={`filter-button ${!showResolved ? "selected" : ""}`} onClick={() => setShowResolved(false)}>Active</button><button className={`filter-button ${showResolved ? "selected" : ""}`} onClick={() => setShowResolved(true)}>Resolved</button></div><div className="grid gap-4 lg:grid-cols-2">{data.events.filter(e => showResolved ? e.status === "resolved" : e.status === "active").map(e => <EventCard key={e.id} event={e} label={e.vesselId ? data.vessels.find(v => v.id === e.vesselId)?.name : e.portId ? data.ports.find(p => p.id === e.portId)?.nameEn : e.voyageId ? data.voyages.find(v => v.id === e.voyageId)?.voyageNumber : undefined} />)}</div></>}</ShippingShell> }

export function FeedPage() { const { data, isLoading, isError } = useShipping(); return <ShippingShell>{isLoading ? <LoadingState /> : isError || !data ? <ErrorState /> : <><PageTitle eyebrow="Information feed" title="Shipping Feed" description="Structured port notices, weather signals and carrier information persisted as feed_items." /><div className="grid gap-4 lg:grid-cols-2">{data.feedItems.map(item => <article key={item.id} className="data-card"><div className="flex items-center justify-between"><Severity value={item.severity} /><StatusBadge stale={item.stale} sourceStatus={item.sourceStatus} /></div><h2 className="mt-3 text-xl font-bold">{item.title}</h2><p className="mt-2 op-70">{item.summary}</p><div className="mt-4 flex flex-wrap gap-3 text-xs op-60"><span>{item.category.replace(/_/g, " ")}</span><span>{formatDate(item.publishedAt)}</span><span>Source: {item.sourceId}</span></div><a className="mt-4 inline-block text-sm text-primary" href={item.sourceUrl} target="_blank" rel="noreferrer">Open source →</a></article>)}</div></>}</ShippingShell> }

export function SettingsPage() { const { data, isLoading, isError, refetch } = useShipping(); const [saved, setSaved] = useState(false); const [refreshInterval, setRefreshInterval] = useState(15); const [anchoredHours, setAnchoredHours] = useState(2); const [delayMinutes, setDelayMinutes] = useState(60); const [retentionDays, setRetentionDays] = useState(30); const [congestionLevel, setCongestionLevel] = useState("high"); useEffect(() => { if (data) { setRefreshInterval(data.settings.refreshInterval); setAnchoredHours(data.settings.eventThresholds.anchoredHours); setDelayMinutes(data.settings.eventThresholds.delayMinutes); setRetentionDays(data.settings.retentionDays); setCongestionLevel(data.settings.eventThresholds.congestionLevel) } }, [data]); if (isLoading) return <ShippingShell><LoadingState /></ShippingShell>; if (isError || !data) return <ShippingShell><ErrorState /></ShippingShell>; return <ShippingShell><PageTitle eyebrow="Local configuration" title="Settings" description="Configure refresh and deterministic event thresholds. Watch state lives on vessels and ports." /><div className="section-panel max-w-2xl"><label className="setting-row"><span><strong>Refresh interval</strong><small>Minutes between local refreshes</small></span><input value={refreshInterval} onChange={e => setRefreshInterval(Number(e.target.value))} type="number" min="1" /></label><label className="setting-row"><span><strong>Anchored alert threshold</strong><small>Hours before an anchored event appears</small></span><input value={anchoredHours} onChange={e => setAnchoredHours(Number(e.target.value))} type="number" min="1" /></label><label className="setting-row"><span><strong>ETA delay threshold</strong><small>Minutes before a voyage delay is elevated</small></span><input value={delayMinutes} onChange={e => setDelayMinutes(Number(e.target.value))} type="number" min="1" /></label><label className="setting-row"><span><strong>Congestion threshold</strong><small>Alert at or above this port level</small></span><select value={congestionLevel} onChange={e => setCongestionLevel(e.target.value)}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label className="setting-row"><span><strong>Retention</strong><small>Days for events and feed items</small></span><input value={retentionDays} onChange={e => setRetentionDays(Number(e.target.value))} type="number" min="1" /></label><button className="primary-button mt-6" onClick={async () => { await myFetch("/shipping/settings", { method: "POST", body: { refreshInterval, retentionDays, eventThresholds: { anchoredHours, delayMinutes, congestionLevel } } }); await refetch(); setSaved(true) }}>{saved ? "Saved locally" : "Save settings"}</button><p className="mt-4 text-sm op-60">Provider mode: Mock · Real AIS, port, schedule and weather adapters: deferred.</p></div></ShippingShell> }

function WatchButton({ kind, id, watched, onSaved }: { kind: "vessel" | "port", id: string, watched: boolean, onSaved: () => void }) {
  return <button className="absolute right-7 top-7 z-2 rounded-lg bg-base/80 px-3 py-2 text-sm text-primary shadow" onClick={async (event) => { event.preventDefault(); await myFetch("/shipping/watch", { method: "POST", body: { kind, id } }); onSaved() }}>{watched ? "Watching" : "Watch"}</button>
}
