/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortsIdRouteImport } from './routes/ports_.$id'
import { Route as FeedIdRouteImport } from './routes/feed_.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsIdRoute = PortsIdRouteImport.update({
  id: '/ports_/$id',
  path: '/ports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedIdRoute = FeedIdRouteImport.update({
  id: '/feed_/$id',
  path: '/feed/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/ports': typeof PortsRoute
  '/settings': typeof SettingsRoute
  '/feed/$id': typeof FeedIdRoute
  '/ports/$id': typeof PortsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/ports': typeof PortsRoute
  '/settings': typeof SettingsRoute
  '/feed/$id': typeof FeedIdRoute
  '/ports/$id': typeof PortsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/events': typeof EventsRoute
  '/feed': typeof FeedRoute
  '/ports': typeof PortsRoute
  '/settings': typeof SettingsRoute
  '/feed_/$id': typeof FeedIdRoute
  '/ports_/$id': typeof PortsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/events'
    | '/feed'
    | '/ports'
    | '/settings'
    | '/feed/$id'
    | '/ports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/events'
    | '/feed'
    | '/ports'
    | '/settings'
    | '/feed/$id'
    | '/ports/$id'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/events'
    | '/feed'
    | '/ports'
    | '/settings'
    | '/feed_/$id'
    | '/ports_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  EventsRoute: typeof EventsRoute
  FeedRoute: typeof FeedRoute
  PortsRoute: typeof PortsRoute
  SettingsRoute: typeof SettingsRoute
  FeedIdRoute: typeof FeedIdRoute
  PortsIdRoute: typeof PortsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports_/$id': {
      id: '/ports_/$id'
      path: '/ports/$id'
      fullPath: '/ports/$id'
      preLoaderRoute: typeof PortsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed_/$id': {
      id: '/feed_/$id'
      path: '/feed/$id'
      fullPath: '/feed/$id'
      preLoaderRoute: typeof FeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  EventsRoute: EventsRoute,
  FeedRoute: FeedRoute,
  PortsRoute: PortsRoute,
  SettingsRoute: SettingsRoute,
  FeedIdRoute: FeedIdRoute,
  PortsIdRoute: PortsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
